version: "3.3"

services:

  todo-mongo:
    build: ./infrastructure/todo-mongo
    image: "todo-spring-microservices/todo-mongo:3-0.1.0"
    restart: always
    volumes:
      - "./infrastructure/todo-mongo/js-scripts:/mongo-js-scripts"
      - "./infrastructure/todo-mongo/init-scripts:/docker-entrypoint-initdb.d"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: admin
      MONGO_AUTH_DB: todo_auth
      MONGO_AUTH_USERNAME: todo_auth
      MONGO_AUTH_PASSWORD: todo_auth
      MONGO_LIST_DB: todo_list
      MONGO_LIST_USERNAME: todo_list
      MONGO_LIST_PASSWORD: todo_list

  todo-mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - todo-mongo
    ports:
      - 9999:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_SERVER: todo-mongo
      ME_CONFIG_MONGODB_PORT: 27017

  todo-config-server:
    image: "todo-spring-microservices/todo-config-server:0.1.0"
    restart: always
    ports:
      - 8800:8800

  todo-eureka-server:
    image: "todo-spring-microservices/todo-eureka-server:0.1.0"
    restart: always
    depends_on:
      - todo-config-server
    ports:
      - 8801:8801
    environment:
      CONFIG_HOST: todo-config-server
      CONFIG_PORT: 8800

  todo-zuul-server:
    image: "todo-spring-microservices/todo-zuul-server:0.1.0"
    restart: always
    depends_on:
      - todo-config-server
      - todo-eureka-server
    ports:
      - 8000:8000
    environment:
      CONFIG_HOST: todo-config-server
      CONFIG_PORT: 8800
      EUREKA_HOST: todo-eureka-server
      EUREKA_PORT: 8801

  todo-auth-service:
    image: "todo-spring-microservices/todo-auth-service:0.1.0"
    restart: always
    depends_on:
      - todo-mongo
      - todo-config-server
      - todo-eureka-server
      - todo-zuul-server
    ports:
      - 9001:8001
    environment:
      MONGO_HOST: todo-mongo
      MONGO_PORT: 27017
      MONGO_AUTH_DB: todo_auth
      MONGO_AUTH_USERNAME: todo_auth
      MONGO_AUTH_PASSWORD: todo_auth
      CONFIG_HOST: todo-config-server
      CONFIG_PORT: 8800
      EUREKA_HOST: todo-eureka-server
      EUREKA_PORT: 8801
      ZUUL_HOST: todo-zuul-server
      ZUUL_PORT: 8000

  todo-list-service:
    image: "todo-spring-microservices/todo-list-service:0.1.0"
    restart: always
    depends_on:
      - todo-mongo
      - todo-config-server
      - todo-eureka-server
      - todo-zuul-server
      - todo-auth-service
    ports:
      - 9002:8002
    environment:
      MONGO_HOST: todo-mongo
      MONGO_PORT: 27017
      MONGO_LIST_DB: todo_list
      MONGO_LIST_USERNAME: todo_list
      MONGO_LIST_PASSWORD: todo_list
      CONFIG_HOST: todo-config-server
      CONFIG_PORT: 8800
      EUREKA_HOST: todo-eureka-server
      EUREKA_PORT: 8801
      ZUUL_HOST: todo-zuul-server
      ZUUL_PORT: 8000
