version: "3.3"

services:

  todo-mongo:
    build: ./infrastructure/todo-mongo
    image: "todo-spring-microservices/todo-mongo:3-0.1.0"
    restart: always
    volumes:
      - "./infrastructure/todo-mongo/js-scripts:/mongo-js-scripts"
      - "./infrastructure/todo-mongo/init-scripts:/docker-entrypoint-initdb.d"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: admin
      MONGO_AUTH_DB: todo_auth
      MONGO_AUTH_USERNAME: todo_auth
      MONGO_AUTH_PASSWROD: todo_auth

  todo-config-server:
    image: "todo-spring-microservices/todo-config-server:0.1.0"
    restart: always
    ports:
      - 8888:8888

  todo-service-discovery-server:
    image: "todo-spring-microservices/todo-service-discovery-server:0.1.0"
    depends_on:
      - todo-config-server
    restart: always
    ports:
      - 8761:8761
    environment:
      CONFIG_HOST: todo-config-server
      CONFIG_PORT: 8888

  todo-gateway-server:
    image: "todo-spring-microservices/todo-gateway-server:0.1.0"
    depends_on:
      - todo-config-server
      - todo-service-discovery-server
    restart: always
    ports:
      - 8080:8080
    environment:
      CONFIG_HOST: todo-config-server
      CONFIG_PORT: 8888
      SERVICE_DISCOVERY_HOST: todo-service-discovery-server
      SERVICE_DISCOVERY_PORT: 8761

  todo-auth-service:
    image: "todo-spring-microservices/todo-auth-service:0.1.0"
    depends_on:
      - todo-mongo
      - todo-config-server
      - todo-service-discovery-server
      - todo-gateway-server
    restart: always
    ports:
      - 9001:9001
    environment:
      MONGO_HOST: todo-mongo
      MONGO_PORT: 27017
      MONGO_AUTH_DB: todo_auth
      MONGO_AUTH_USERNAME: todo_auth
      MONGO_AUTH_PASSWROD: todo_auth
      CONFIG_HOST: todo-config-server
      CONFIG_PORT: 8888
      SERVICE_DISCOVERY_HOST: todo-service-discovery-server
      SERVICE_DISCOVERY_PORT: 8761
      GATEWAY_HOST: todo-gateway-server
      GATEWAY_PORT: 8080
