logging:
  level:
    io.agatsenko.todo: DEBUG
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${SERVICE_DISCOVERY_HOST:localhost}:${SERVICE_DISCOVERY_PORT:8801}/eureka/
    registerWithEureka: true
    fetchRegistry: true
