logging:
  level:
    io.agatsenko.todo: DEBUG
    org.springframework: INFO

server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8801}/eureka/
    registerWithEureka: true
    fetchRegistry: true

zuul:
  host:
    connect-timeout-millis: 2000
    socket-timeout-millis: 2000
  ignoredServices: "*"
#  ignoredPatterns:
#    - /**/actuator/**
#    - /**/swagger-ui.html
#    - /**/swagger/v2/api-docs
#    - /**/swagger-resources/**
#    - /**/webjars/springfox-swagger-ui/**
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    auth-service:
      serviceId: todo-auth-service
      path: /uaa/**
      stripPrefix: false
    list-service:
      serviceId: todo-list-service
      path: /list/**
      stripPrefix: false

ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 2000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

management:
  endpoints:
    web:
      exposure:
        include: "*"
