logging:
  level:
    io.agatsenko.todo: DEBUG
    org.springframework: INFO

server:
  port: 8001
  servlet:
    contextPath: /uaa

persistence:
  mongodb:
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT:27017}
    database: ${MONGO_AUTH_DB:todo_auth}
    username: ${MONGO_AUTH_USERNAME:todo_auth}
    password: ${MONGO_AUTH_PASSWORD:todo_auth}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8801}/eureka/
    registerWithEureka: true
    fetchRegistry: true

security:
  oauth2:
    # 1 hour
    accessTokenValiditySeconds: 3600
    # 24 hours
    refreshTokenValiditySeconds: 86400
    # command of key store generation:
    # keytool -genkeypair -alias jwt -keyalg RSA -keysize 2048 -keypass todo-spring-microservices -keystore jwt-keystore.jks -storepass todo-spring-microservices
    # note:
    # a password should be same for key store and key pair
    # details see in https://dzone.com/articles/50-common-java-errors-and-how-to-avoid-them-part-2 BadPaddingException
    jwt:
      keyStore: "classpath:jwt-keystore.jks"
      keyStorePassword: todo-spring-microservices
      keyPairAlias: jwt
      keyPairPassword: todo-spring-microservices
    clients:
      browser:
        clientId: browser
        scope:
          - ui
        authorizedGrantTypes:
          - password
          - refresh_token
      swagger:
        clientId: swagger
        encodedSecret: $2a$10$GuVIec22r/8Ls0npXBNrZeXMAxxb43kdIoCyjgjPVelALMBnAOXPO
        decodedSecret: a0C8wSjDXwYEAwsiFiJ3
        scope:
          - ui
          - server
        authorizedGrantTypes:
          - password
          - refresh_token
      todo-list-service:
        clientId: todo-list-service
        encodedSecret: $2a$10$bEr4lfESnKC38SgyMimtm.sVvM1GyWJ/DvRTGOz2U1OC0z/TJRiZG
        decodedSecret: Ylr8wcHtv0FJisP7ZQqP
        scope:
          - server
        authorizedGrantTypes:
          - client_credentials
  whitelistUrlPatterns:
    - /*.ico
    - /webjars/**
    - /actuator/**
    - /swagger/v2/api-docs/**
    - /swagger-resources/**
    - /swagger-ui.html

ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 2000

management:
  endpoints:
    web:
      exposure:
        include: "*"

swagger:
  security:
    defaultClientId: swagger
    tokenEndpointUrl: http://${ZUUL_HOST:localhost}:${ZUUL_PORT:8000}/uaa/oauth/token
    authorizeEndpointUrl: http://${ZUUL_HOST:localhost}:${ZUUL_PORT:8000}/uaa/oauth/authorize

springfox.documentation.swagger.v2.path: /swagger/v2/api-docs

