server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: health

zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  ignoredServices: "*"
  ignoredPatterns:
    - /**/actuator/**
    - /**/swagger-ui.html
    - /**/swagger/v2/api-docs
    - /**/swagger-resources/**
    - /**/webjars/springfox-swagger-ui/**
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    auth-service:
      serviceId: todo-auth-service
      path: /uaa/**
      stripPrefix: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
