logging:
  level:
    io.agatsenko.todo: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://todo-service-discovery-server:9101/eureka/
