logging:
  level:
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://todo-eureka-server:9101/eureka/
