management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: ${CONFIG_PORT:8888}

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-locations: classpath:/config/{profile}/{label}
          search-locations: classpath:/configs

